-- NAC 准入控制表
CREATE TABLE IF NOT EXISTS nac_policies (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT DEFAULT 1 NOT NULL,
  name VARCHAR(200) NOT NULL,
  description TEXT,
  priority INT DEFAULT 100,
  is_active BOOLEAN DEFAULT TRUE,
  conditions JSON NOT NULL,
  auth_method ENUM('802.1x','portal','mac','ppsk','bypass'),
  actions JSON NOT NULL,
  version INT DEFAULT 1,
  created_by BIGINT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_tenant (tenant_id),
  INDEX idx_priority (priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS nac_sessions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT DEFAULT 1 NOT NULL,
  mac_address VARCHAR(17) NOT NULL,
  ip_address VARCHAR(45),
  username VARCHAR(100),
  auth_method VARCHAR(20),
  vlan_id INT,
  switch_ip VARCHAR(45),
  switch_port VARCHAR(50),
  ssid VARCHAR(100),
  compliance_status ENUM('compliant','non_compliant','quarantined','unknown') DEFAULT 'unknown',
  compliance_score INT DEFAULT 0,
  session_start DATETIME DEFAULT CURRENT_TIMESTAMP,
  last_activity DATETIME DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT TRUE,
  INDEX idx_tenant (tenant_id),
  INDEX idx_mac (mac_address),
  INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS nac_auth_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT DEFAULT 1 NOT NULL,
  mac_address VARCHAR(17) NOT NULL,
  ip_address VARCHAR(45),
  username VARCHAR(100),
  auth_method VARCHAR(20),
  result ENUM('success','failed','rejected') NOT NULL,
  failure_reason VARCHAR(500),
  switch_ip VARCHAR(45),
  switch_port VARCHAR(50),
  ssid VARCHAR(100),
  policy_id BIGINT,
  assigned_vlan INT,
  details JSON,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  INDEX idx_tenant (tenant_id),
  INDEX idx_mac (mac_address),
  INDEX idx_result (result),
  INDEX idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS visitor_accounts (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT DEFAULT 1 NOT NULL,
  visitor_name VARCHAR(100) NOT NULL,
  visitor_company VARCHAR(200),
  visitor_phone VARCHAR(20),
  username VARCHAR(100) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  sponsor_name VARCHAR(100),
  sponsor_department VARCHAR(200),
  access_level ENUM('internet_only','limited','full') DEFAULT 'internet_only',
  vlan_id INT,
  valid_from DATETIME DEFAULT CURRENT_TIMESTAMP,
  valid_until DATETIME NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  INDEX idx_tenant (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 终端管理表
CREATE TABLE IF NOT EXISTS terminals (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT DEFAULT 1 NOT NULL,
  hostname VARCHAR(255),
  ip_address VARCHAR(45),
  mac_address VARCHAR(17),
  terminal_type ENUM('windows_pc','mac','linux','android','ios','printer','camera','iot','unknown') DEFAULT 'unknown',
  os_type VARCHAR(100),
  os_version VARCHAR(100),
  manufacturer VARCHAR(200),
  model VARCHAR(200),
  cpu_info VARCHAR(200),
  memory_gb DECIMAL(10,2),
  disk_gb DECIMAL(10,2),
  user_name VARCHAR(100),
  user_department VARCHAR(200),
  user_id BIGINT,
  switch_ip VARCHAR(45),
  switch_port VARCHAR(50),
  vlan_id INT,
  status ENUM('active','idle','repair','retired') DEFAULT 'active',
  is_online BOOLEAN DEFAULT FALSE,
  last_online_at DATETIME,
  last_offline_at DATETIME,
  offline_days INT DEFAULT 0,
  compliance_score INT DEFAULT 0,
  compliance_status ENUM('compliant','non_compliant','unknown') DEFAULT 'unknown',
  antivirus_installed BOOLEAN,
  antivirus_updated BOOLEAN,
  firewall_enabled BOOLEAN,
  os_patched BOOLEAN,
  tags JSON,
  group_ids JSON,
  custom_fields JSON,
  discovery_method VARCHAR(50),
  first_seen_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  approval_status ENUM('approved','pending','blacklisted') DEFAULT 'pending',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_tenant (tenant_id),
  INDEX idx_hostname (hostname),
  INDEX idx_ip (ip_address),
  INDEX idx_mac (mac_address),
  INDEX idx_type (terminal_type),
  INDEX idx_online (is_online),
  INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS terminal_groups (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT DEFAULT 1 NOT NULL,
  name VARCHAR(200) NOT NULL,
  description TEXT,
  group_type ENUM('static','dynamic') DEFAULT 'static',
  dynamic_conditions JSON,
  security_policy_id BIGINT,
  network_policy JSON,
  terminal_count INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  INDEX idx_tenant (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
